### ISSUE TITLE
Tabellen op mobiel

### ISSUE THREAD

**Issue by Nierot** [ODDInvictus/ibs3#142]
kan niet horizontaal scrollen, zie strafbakken

**Comment by Nierot** [comment]
+ email aliassen

**Comment by Astronautilus14** [comment]
Als je telefoon te smal is voor strafbakken moet je maar een nomale telefoon kopen

**Comment by Nierot** [comment]
ja dit is stuk gegaan nadat ik het heb gesloopt vanavond haha

**Comment by Astronautilus14** [comment]
duplicate van #138
