### ISSUE TITLE
Prisma updaten

### ISSUE THREAD

**Issue by Nierot** [ODDInvictus/ibs3#157]
We draaien nu 4.7.0
Prisma 5 is uit.

Dit kan niet zomaar geupdate worden, aangezien we middleware gebruiken (en dat is deprecated in 4.16.0)

**Comment by Astronautilus14** [comment]
de `previewFeatures` kunnen hier ook weg

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["filteredRelationCount", "orderByNulls"]
}
```

**Comment by Astronautilus14** [comment]
Verder zie ik vgm niks wat wij gebruiken in de [upgrade guide](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5)

**Comment by Nierot** [comment]
Checklist


- [ ]    Minimum Node.js version change to 16.13.0
- [ ]     Minimum TypeScript version change to 4.7
- [ ]     Minimum PostgreSQL version change to 9.6
- [ ]     Prisma Client embedded SQLite version upgrade to 3.41.2
- [ ]     Removal of rejectOnNotFound property
- [ ]     Removal of some array shortcuts
- [ ]     cockroachdb provider is now required when connecting to a CockroachDB database
- [ ]     Removed runtime/index.js from the generated Prisma Client
- [ ]     Removal of deprecated flags in the Prisma CLI
- [ ]     Removal of the beforeExit hook from the library engine
- [ ]     Removal of deprecated prisma2 executable
- [ ]     Removal of deprecated experimentalFeatures generator property in the Prisma schema
- [ ]     Renamed migration-engine to schema-engine

**Comment by Nierot** [comment]
Mmm middleware is pas gedeprecate op 4.16, 1 versie voor 5.0, nog niet geremoved
