### ISSUE TITLE
Ruim dependencies op

### ISSUE THREAD

**Issue by Nierot** [ODDInvictus/ibs3#168]
We hebben een boel dependencies die of nauwelijks nodig of totaal onnodig zijn.

Dit is jammer want het maakt de bundlesize groter -> ibs is langzamer

**Comment by Nierot** [comment]
@popper/js

PS C:\Users\Niels\ibs3> npm ls @popper/js
ibs3@0.0.1 C:\Users\Niels\ibs3
└── (empty)

**Comment by Nierot** [comment]
flowbite

PS C:\Users\Niels\ibs3> npm ls flowbite      
ibs3@0.0.1 C:\Users\Niels\ibs3
├─┬ flowbite-svelte@0.29.13
│ └── flowbite@1.7.0 deduped
└── flowbite@1.7.0

PS C:\Users\Niels\ibs3> npm ls flowbite-svelte
ibs3@0.0.1 C:\Users\Niels\ibs3
└── flowbite-svelte@0.29.13

**Comment by Nierot** [comment]
tailwindcss

Dit wordt (zover ik kan zien) gebruikt in:
`(app)/+layout.svelte` (half css/half tailwind)
`strafbakken/` alleen om de `<a>` te stylen lol

Genoeg reden om dit er gewoon uit te werken

PS C:\Users\Niels\ibs3> npm ls tailwindcss    
ibs3@0.0.1 C:\Users\Niels\ibs3
└── tailwindcss@3.3.3

**Comment by Astronautilus14** [comment]
> 

Oeh gaan we dan skeleton ui gebruiken?

**Comment by Nierot** [comment]
ja kan wel, moeten we wel best wat herschijven haha

**Comment by Nierot** [comment]
echter vind ik themas wel nice

**Comment by Nierot** [comment]
Gefixt in #173
