### ISSUE TITLE
Vervang 'redirect in een paar tellen' met flash messages

### ISSUE THREAD

**Issue by Astronautilus14** [ODDInvictus/ibs3#171]
Je hebt een library `svelte-flash-messages` die toasts met redirects combineert zodat je eenvoudig de toast op de nieuwe pagina kan laten zien.

[YouTube video](https://www.youtube.com/watch?v=hB6OkaYWS5I) hoe ik aan het idee kwam.

p.s. Terwijl ik dit zit te typen vraag ik me erg af of dat niet gewoon sowieso kan omdat de toast component in de root zit.

**Comment by Nierot** [comment]
ja goeie, kan prima eigenlijk

**Comment by Nierot** [comment]
enige reden dat ze er nu zijn is omdat hij de reload niet overleed
