### ISSUE TITLE
PWA Wil short links openen

### ISSUE THREAD

**Issue by Astronautilus14** [ODDInvictus/ibs3#200]
En dat werkt wel maar is gewoon niet wat je wilt

**Comment by Nierot** [comment]
Dat komt door "deeplinks" en gebeurt omdat dat nog niet is ingesteld in de `manifest.json`. Om dit te fixen moet er iets gebeuren met de `capture_links`

**Comment by Nierot** [comment]
TODO: even testen wanneer v2 uit is.

**Comment by Astronautilus14** [comment]
Lijkt gefixt
