### ISSUE TITLE
Persoonlijke mobiele menu bar

### ISSUE THREAD

**Issue by Astronautilus14** [ODDInvictus/ibs3#204]
Dat je zelf kan kiezen wat er in de menubalk komt

**Comment by Nierot** [comment]
![image](https://github.com/ODDInvictus/ibs3/assets/56843328/6509acaa-12ee-4557-95e0-77d4ebdaf769)
Ik heb nu dit gebakken van de mobiele UI (met zo'n hamburger menu knopje)

**Comment by Nierot** [comment]
sluit want de oplossing in v2 is prima
