### ISSUE TITLE
Svelte ssr cache

### ISSUE THREAD

**Issue by SimplyPancake** [ODDInvictus/ibs3#22]
Aangezien we SSR doen, dan willen we ook een cache!
https://stackoverflow.com/questions/69524905/sveltekit-and-caching-the-component-output-in-server-side-rendering

Zie
https://github.com/svelte-drama/swr
https://github.com/ConsoleTVs/sswr

**Comment by Nierot** [comment]
Ik heb Redis opgezet, nu nog cachen lmao
