### ISSUE TITLE
'Ik ben niet bij' update ui niet en is stuk

### ISSUE THREAD

**Issue by Astronautilus14** [ODDInvictus/ibs3#226]
Als je eerste reactie is dat je niet bij bent doet dat niks (in ieder geval als je de eerste bent die reageert). Het update de ui niet en slaat het ook niet op. Als je wisseld van bij naar niet bij wordt dit wel goed opgeslagen naar update de ui naar grijs/geen reactie totdat je refresht.

**Comment by Nierot** [comment]
Gefixt in #277
