### ISSUE TITLE
Instellingen stuk

### ISSUE THREAD

**Issue by Nierot** [ODDInvictus/ibs3#263]
![Screenshot_20231030-161418.jpg](https://github.com/ODDInvictus/ibs3/assets/56843328/9b44caa2-3354-4387-8bb5-d05d69fd5f15)

**Comment by WoutDrowniak** [comment]
Bij mij werkt het op iOS wel en op mijn laptop ook

**Comment by Nierot** [comment]
Als je een instelling veranderd ook? Ik krijg een 400 bij opslaan-------- Oorspronkelijk bericht --------Op 16-03-2024 16:30, schreef Wout :
Bij mij werkt het op iOS wel en op mijn laptop ook

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ODDInvictus/ibs3/issues/263#issuecomment-2002021225",
"url": "https://github.com/ODDInvictus/ibs3/issues/263#issuecomment-2002021225",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Astronautilus14** [comment]
De email preferences is stuk, thema's werken wel

**Comment by Astronautilus14** [comment]
De frontend stuurt een request met een 'action' in de body. Dit is of 'edit' of 'revert'. De backend checked vervolgens of action 'set' of 'theme' is. Dus dat werkt natuurlijk niet

**Comment by Nierot** [comment]
Fixed in #374
