### ISSUE TITLE
Naming convention prisma fields

### ISSUE THREAD

**Issue by Astronautilus14** [ODDInvictus/ibs3#266]
Soms hebben fields een hoofdletter en soms niet. Het is vanwege de autogegeneerde types niet echt een issue, in hun eigen docs zijn ze hier ook niet consistent mee. Ik zou alle scalar fields (int, string etc.) met kleine letter beginenn en alle relational fields met een hoofdletter, zodat het bij een input leesbaarder is waar je uit een andere table aan het queryen bent. Dit doen we ook al op veel plekken.

**Comment by Nierot** [comment]
Leuk idee, maar dan moeten we eerst op elke pagina types toevoegen, anders wordt dit een nachtmerrie aan bugs.
+ testing wordt dan wel noodzakelijk, anders introduceren we een heleboel bugs haha

**Comment by Nierot** [comment]
Dit gaat echt nooit werken lol
