### ISSUE TITLE
Ongeveer bugs

### ISSUE THREAD

**Issue by Nierot** [ODDInvictus/ibs3#318]
Naut:
- [x] #324
- [ ] /ongeveer/purchases/create?type=INVOICE
- [x] #322
- [x] #327

Niels:
- [x] toasts kleine letter
- [x] toasts nederlands
- [ ] fail2ban
- [ ] persoonlijke email factuur

// TODOS @niels

**Comment by Nierot** [comment]
@Astronautilus14 hoe doe ik een product inactief maken? ik zie allen verwijderen?

**Comment by Astronautilus14** [comment]
> @Astronautilus14 hoe doe ik een product inactief maken? ik zie allen verwijderen?

op de edit pagina maar die is stuk zie ik

**Comment by Astronautilus14** [comment]
De toast heeft een kleine letter omdat hij niet de titel pakt maar het type kom ik net achter :)
