### ISSUE TITLE
Persoonlijke playlist toont je eigen na de eerste pagina

### ISSUE THREAD

**Issue by brokhiv** [ODDInvictus/ibs3#337]
Stappen voor reproductie:

1. Ga naar de Playlist -> Nieuwe track
2. Klik een ander lid aan om zijn playlist te bekijken
![image](https://github.com/ODDInvictus/ibs3/assets/46261484/4061aba7-51ff-4cbc-9e95-88c7f1365193)
3. Ga naar de tweede pagina
![image](https://github.com/ODDInvictus/ibs3/assets/46261484/c8c05ac9-fce5-4fea-b3c2-2ad4b73d57d4)
4. Je bekijkt nu je eigen playlist
![image](https://github.com/ODDInvictus/ibs3/assets/46261484/9bc63bf6-a5da-4210-af98-9ca760cad4bd)

**Comment by brokhiv** [comment]
Vermoedelijke bron van de bug:
![image](https://github.com/ODDInvictus/ibs3/assets/46261484/89e18b6e-2acc-4ca6-9084-bce7ca706067)

**Comment by Nierot** [comment]
#246

**Comment by Nierot** [comment]
Haha ja hij gebruikt `data.user` i.p.v. `data.playlistUser` vanaf pagina `> 1`

**Comment by Nierot** [comment]
Fixed in https://github.com/ODDInvictus/ibs3/commit/f55e8620f53f2cbdcff9cd5e2700a01206602001
