### ISSUE TITLE
Singleton voor databases (o.i.d)

### ISSUE THREAD

**Issue by Nierot** [ODDInvictus/ibs3#338]
Builds gaan stuk, al een tijdje. Ik heb nu een idee hoe dit gefixt kan worden. Maak van prisma en mongo een singleton!

Het probleem is dat `const db = new PrismaClient()` wordt geevalueert tijdens de compile, waardoor hij probeert te verbinden en dat is helemaal kut. Als we hier dit achter een init() gooien en die op opstarten afvuren, dan gebeurt dit niet tijdens de compile.

**Comment by Nierot** [comment]
Een optie hiervoor is https://github.com/ODDInvictus/ibs3/tree/issue/338 , maar dat is helemaal kut met types enzo
Ik denk dat het beter is als we iets doen als:
```ts
class Database {
  #mongo
  #redis
  #prisma

  initialize() {
    // Maak nieuwe instantie van mongo/redis/prisma-client
  }

  db() {
    if (!prisma) initialize()
    return this.#prisma
  } 
}

export const db = new Database()
```

Beter zou zijn als initialize gerunt wordt zodra de server opstart, maar kan niet zo 1 2 3 vinden of Sveltekit dit ondersteund

**Comment by Astronautilus14** [comment]
Alles wat je in hooks.server.ts zet runt bij het opstarten van de server

**Comment by Nierot** [comment]
das niet waar, hooks.server.ts wordt pas geëvalueerd op de 1e request, maar werkt goed genoeg voor ons

**Comment by Nierot** [comment]
maar voor builds heb je hetzelfde probleem
