### ISSUE TITLE
Users pagina

### ISSUE THREAD

**Issue by Astronautilus14** [ODDInvictus/ibs3#35]
- [x] Commissie maken
- [x] Commissie verwijderen
- [x] Lid toevoegen aan commissie
- [x] Lid verwijderen van commissie
- [ ] Lid verwijderen
- [ ] Feut maken
- [ ] Feut lid maken
- [ ] Use details weergeven
- [ ] User details veranderen

**Comment by Nierot** [comment]
De meeste van deze dingen kan al geregeld worden vanuit Authentik, onze auth provider. Zoals commissies maken, leden toevoegen/verwijderen, gebruikers verwijderen

**Comment by Nierot** [comment]
Daaren tegen een gebruikerspagina waar je je data kan aanpassen is wel weer nice
